### PR TITLE
incomplete cli prototype

### PR DESCRIPTION
**Pull request by butonic**
Edit @IljaN 

First rudimentary version of ocis-accounts-cli

ocis-accounts [list|delete|update|add|inspect]

Implements UpdateMask for the update request. Changed server-handler accordingly.
The commands use service-discovery to discover the backend.

Demo Video: https://www.youtube.com/watch?v=tL8qWnIWDSY

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/accountupdate.go  2
- pkg/command/accountadd.go  2
- pkg/flagset/flagset.go  1
         

Clones added
============
- pkg/flagset/flagset.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/accountupdate.go  2
- pkg/command/accountadd.go  2
- pkg/flagset/flagset.go  1
         

Clones added
============
- pkg/flagset/flagset.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/update.go  2
- pkg/command/create.go  2
- pkg/flagset/flagset.go  1
         

Clones added
============
- pkg/command/update.go  1
- pkg/command/create.go  1
- pkg/flagset/flagset.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/list.go  2
- pkg/flagset/flagset.go  1
- pkg/command/create.go  2
- pkg/command/update.go  2
         

Clones added
============
- pkg/command/list.go  1
- pkg/flagset/flagset.go  4
- pkg/command/create.go  1
- pkg/command/update.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/view.go  3
- pkg/command/list.go  2
- pkg/command/create.go  2
- pkg/flagset/flagset.go  1
- pkg/command/update.go  2
         

Clones added
============
- pkg/command/view.go  1
- pkg/command/list.go  2
- pkg/command/create.go  2
- pkg/flagset/flagset.go  4
- pkg/command/update.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/list.go  2
- pkg/flagset/flagset.go  1
- pkg/command/create.go  2
- pkg/command/view.go  3
- pkg/command/update.go  2
         

Clones added
============
- pkg/command/list.go  2
- pkg/flagset/flagset.go  4
- pkg/command/create.go  2
- pkg/command/view.go  1
- pkg/command/update.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/create.go  2
- pkg/command/view.go  3
- pkg/command/list.go  2
- pkg/flagset/flagset.go  1
- pkg/command/delete.go  3
- pkg/command/update.go  2
         

Clones added
============
- pkg/command/create.go  3
- pkg/command/view.go  2
- pkg/command/list.go  3
- pkg/flagset/flagset.go  4
- pkg/command/delete.go  3
- pkg/command/update.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/create.go  2
- pkg/command/list.go  2
- pkg/command/view.go  3
- pkg/command/delete.go  3
- pkg/command/update.go  2
- pkg/flagset/flagset.go  1
         

Clones added
============
- pkg/command/create.go  3
- pkg/command/list.go  3
- pkg/command/view.go  2
- pkg/command/delete.go  3
- pkg/command/update.go  3
- pkg/flagset/flagset.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/inspect_account.go  3
- pkg/command/list_accounts.go  2
- pkg/command/remove_account.go  3
- pkg/service/v0/accounts.go  1
- pkg/command/update_account.go  4
- pkg/command/add_account.go  2
- pkg/flagset/flagset.go  1
         

Clones added
============
- pkg/command/inspect_account.go  1
- pkg/command/remove_account.go  1
- pkg/flagset/flagset.go  25
         

Clones removed
==============
+ pkg/service/v0/accounts.go  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by IljaN** [comment]
ocis-accounts [list|delete|update|add|inspect]

Implements UpdateMask for the update request. Changed server-handler accordingly.
The commands use service-discovery to discover the backend.

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/list_accounts.go  2
- pkg/command/inspect_account.go  3
- pkg/service/v0/accounts.go  1
- pkg/flagset/flagset.go  1
- pkg/command/update_account.go  4
- pkg/command/remove_account.go  3
- pkg/command/add_account.go  2
         

Clones added
============
- pkg/command/inspect_account.go  1
- pkg/flagset/flagset.go  25
- pkg/command/remove_account.go  1
         

Clones removed
==============
+ pkg/service/v0/accounts.go  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=5887321&bid=19272921)

**Comment by IljaN** [comment]
Continued https://github.com/owncloud/product/issues/115

**Pull request closed without merging**
