### PR TITLE
add query properties, add pb deps, fix pb target

### PR DESCRIPTION
**Pull request by butonic**
fixes https://github.com/owncloud/ocis-accounts/issues/26
first step for https://github.com/owncloud/ocis-proxy/issues/35
prerequisite of https://github.com/owncloud/ocis-accounts/issues/2

### CODE REVIEW

**Comment by butonic** [comment]
running into the same staticcheck mess as https://github.com/owncloud/ocis-hello/pull/61 ...

**Comment by refs** [comment]
seems that https://github.com/owncloud/ocis-accounts/pull/28/files?file-filters%5B%5D=.go&file-filters%5B%5D=.mod&file-filters%5B%5D=.proto&file-filters%5B%5D=No+extension#diff-7a285d2c6dd640b0679850fde59a91a5R10 is deprecated

**Comment by refs** [comment]
As a workaround we could disable staticcheck for generated code

**Comment by refs** [comment]
@butonic alternatively we could add the latest version of saticcheck, create a `vendor` folder and ship the passing version. That should create reproducible builds, and we don't have to depend of upstream because we ship `vendors`.

We could also get rid of the `tools.go` 🤔

**Comment by IljaN** [comment]
vendor ALL the things ;)

**Comment by refs** [comment]
> vendor ALL the things ;)

ohrrn

**Comment by butonic** [comment]
I updated the proto file to
- rename it to `AccountsService`
- introduce a GetRequest that allows using checking multiple properties
- use a Search(Query) instead of List
- use [pagination as recommended](https://cloud.google.com/apis/design/design_patterns) taking an example from https://github.com/googleapis/googleapis/blob/master/google/cloud/resourcemanager/v2/folders.proto#L342-L374

**Comment by butonic** [comment]
disabling the check for the generated files with https://github.com/owncloud/ocis-accounts/pull/28/commits/422ceb9080efad31adf8ef39390f761419cc5a5b#diff-7105639c876a4a09708eac9f08203357

**Pull request merged**
