### PR TITLE
Add create/delete capabilities and UI

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ui/tests/acceptance/pageobjects/accountsPage.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6148293&bid=20094090)

**Review by kulmann — APPROVED** [review]

**Comment by kulmann** [comment]
Screenshot 2020-09-10 at 08 45 46
Screenshot 2020-09-10 at 08 46 38
Screenshot 2020-09-10 at 08 47 10
Screenshot 2020-09-10 at 08 48 18
Screenshot 2020-09-10 at 08 52 56
Screenshot 2020-09-10 at 08 53 05

**Pull request merged**
