### PR TITLE
Prevent creating duplicate accounts

### PR DESCRIPTION
**Pull request by kulmann**

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/service/v0/accounts.go  1
         

Clones added
============
- pkg/service/v0/accounts.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6186768&bid=20189648)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/service/v0/accounts.go  1
         

Clones added
============
- pkg/service/v0/accounts.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6186768&bid=20189648)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/service/v0/accounts.go  1
         

Clones added
============
- pkg/service/v0/accounts.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6186768&bid=20189648)

**Review by IljaN — APPROVED** [review]
LGTM :dancers:

**Pull request merged**
